security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            users:
                user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        secured_area:
            pattern:  ^/
            anonymous: ~
            form_login:
                login_path:   /login
                check_path:   /login_check
                # Configurar la página a la cual es redirigido si no se almacenó una página previa en la sesión
                default_target_path: /admin
                
                #always_use_default_target_path: false
                #use_referer: true
                # opciones para redirigir en ingreso fallido
                failure_path: /login_failure
                # nombres de campo para el nombre de usuario y contraseña
                username_parameter:             _username
                password_parameter:             _password
            logout:
                path:   /logout
                target: /
                    
    access_control:
        #- { path: ^/admin, roles: ROLE_USER }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }