security:
  
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous:  ~
            form_login:
                login_path:  /acceso
                check_path:  /acceso_check
                default_target_path: /
            logout:
                path:   /logout
                target: /
            remember_me:
                key: aSecretKey
                lifetime: 3600
                path: /
                domain: ~ # El valor predeterminado es el dominio actual de $_SERVER               
    
    access_control:
        - { path: ^/perfil        , roles: ROLE_USER }
        - { path: ^/me-apunto-a-* , roles: ROLE_USER }
        - { path: ^/admin         , roles: ROLE_ADMIN }
        - { path: ^/registro      , roles: IS_AUTHENTICATED_ANONYMOUSLY }

    providers:
        main:
            providers: [in_memory, user_db]
        in_memory:
            users:
                admin:     { password: d033e22ae348aeb5660fc2140aec35850c4da997, roles: 'ROLE_ADMIN' }
        user_db:
            entity: { class: NV\ParejasBundle\Entity\Usuarios, property: email }
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm:  sha1
            iterations: 1
            encode_as_base64: false
        NV\ParejasBundle\Entity\Usuarios: sha512
