<?php

namespace NV\ParejasBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LocalidadesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocalidadesRepository extends EntityRepository{
    
    public function findAllByIdProvincia($id){
        
        return $this->getEntityManager()
            ->createQuery('SELECT l.id,l.localidad FROM NVParejasBundle:Localidades l WHERE l.provincia_id = :id ')
            ->setParameter('id', $id)
            ->getResult();        
    
    }        
    
}