<?php

namespace NV\ParejasBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PaisesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaisesRepository extends EntityRepository{
    
    public function findAllOrderedById(){
        
        return $this->getEntityManager()
            ->createQuery('SELECT p.pais FROM NVParejasBundle:Paises p WHERE p.id IN (45,56) ')
            ->getResult();        
    
    }    
    
}