<?php

namespace NV\ParejasBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PerfilesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerfilesRepository extends EntityRepository
{
}