<?php

namespace NV\ParejasBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProvinciasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProvinciasRepository extends EntityRepository
{
    public function findAllByIdPais($id)
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT   p.id, p.provincia
                FROM     NVParejasBundle:Provincias p
                WHERE    p.pais_id = :id
                ORDER BY p.provincia
            ')
            ->setParameter('id', $id)
            ->getResult();
    }
}