webservices_getProvinciasByIdPais:
    pattern:  /getProvinciasByIdPais
    defaults: { _controller: NVParejasBundle:Geo:getProvinciasByIdPais }
    
webservices_getLocalidadesByIdProvincia:
    pattern:  /getLocalidadesByIdProvincia
    defaults: { _controller: NVParejasBundle:Geo:getLocalidadesByIdProvincia }    